/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Corruptions } from "./Corruptions";

export { Corruptions__factory } from "./factories/Corruptions__factory";
